#!/bin/bash

rm -rf $HOME/.local/share/tiny/tmp
mkdir $HOME/.local/share/tiny/tmp
cd $HOME/.local/share/tiny/tmp

MIRROR_SITE=https://mirror.ghproxy.com
RELEASE_PAGE=https://github.com/doitsujin/dxvk/releases
LATEST_DXVK_TAG=$(curl -L $RELEASE_PAGE | grep -oP 'Version \K[^"]*</h2>' | cut -d "<" -f 1 | head -n 1)
if [ -z "$LATEST_DXVK_TAG" ]
then
  LATEST_DXVK_TAG="2.3"
fi
LATEST_DXVK_NAME="dxvk-$LATEST_DXVK_TAG.tar.gz"
LATEST_DXVK_LINK="https://github.com/doitsujin/dxvk/releases/download/v$LATEST_DXVK_TAG/$LATEST_DXVK_NAME"

wget $MIRROR_SITE/$LATEST_DXVK_LINK
if [ $? -ne 0 ]; then
  wget $LATEST_DXVK_LINK
  if [ $? -ne 0 ]; then
    rm -rf $HOME/.local/share/tiny/tmp
    echo '下载失败...退出安装...'
    exit
  fi
fi

wineboot
tar xvf $LATEST_DXVK_NAME
mv dxvk-$LATEST_DXVK_TAG/x32/* ~/.wine/drive_c/windows/syswow64
mv dxvk-$LATEST_DXVK_TAG/x64/* ~/.wine/drive_c/windows/system32

cd ~
rm -rf $HOME/.local/share/tiny/tmp

echo '安装完成，建议前往wine配置更新配置。'