#!/bin/bash

sudo dpkg --add-architecture armhf
sudo apt update
sudo apt upgrade -y
sudo apt install -y cmake gcc-arm-linux-gnueabihf libc6:armhf
sudo apt reinstall -y libc6-dev

mkdir $HOME/.local/share/tiny/cross

mkdir $HOME/.local/share/tiny/tmp
cd $HOME/.local/share/tiny/tmp

git clone https://github.com/ptitSeb/box86
if [ $? -ne 0 ]; then
  git clone https://mirror.ghproxy.com/https://github.com/ptitSeb/box86
  if [ $? -ne 0 ]; then
    rm -rf $HOME/.local/share/tiny/tmp
    echo '仓库克隆失败...退出安装...'
    exit
  fi
fi

git clone https://github.com/ptitSeb/box64
if [ $? -ne 0 ]; then
  git clone https://mirror.ghproxy.com/https://github.com/ptitSeb/box64
  if [ $? -ne 0 ]; then
    rm -rf $HOME/.local/share/tiny/tmp
    echo '仓库克隆失败...退出安装...'
    exit
  fi
fi

cd box86
mkdir build
cd build
cmake .. -DARM64=1 -DBAD_SIGNAL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make
cd ../..
mv box86/build/box86 ../cross

cd box64
mkdir build
cd build
cmake .. -DARM64=1 -DBAD_SIGNAL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make
cd ../..
mv box64/build/box64 ../cross

cd ..
rm -rf tmp

echo '安装完成'
